
export default function Home() {
  return (
    <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen gap-16  font-[family-name:var(--font-geist-sans)]">
      <main className="flex flex-col gap-[32px] row-start-2 items-center sm:items-start">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga assumenda, nobis praesentium culpa tenetur expedita natus reiciendis cumque ipsum, impedit omnis itaque sit quasi quod iure ratione incidunt officia est repellat temporibus dolor earum reprehenderit id obcaecati. Laudantium animi totam, dolor necessitatibus quae quisquam culpa provident placeat adipisci. Tempore natus corporis fugiat magnam laudantium error eligendi maiores eum illum perferendis maxime harum dolore quos, quis aut? Explicabo omnis ipsa exercitationem iste necessitatibus ratione doloremque quo animi ullam veniam quia eaque, nisi, sunt, dicta optio? Blanditiis, velit! Sint corrupti fugit harum expedita ea. Fugiat accusamus soluta, fugit cum harum numquam possimus laboriosam esse porro placeat odit, et ipsum voluptatibus. Accusantium alias in placeat. Excepturi iusto laudantium rerum voluptates exercitationem suscipit aperiam quos dolore dolor saepe eveniet deserunt eaque, quae eum, minus molestiae dicta odio ut tempora doloremque aut. Numquam vitae reprehenderit consectetur facilis voluptatum, animi id non minima dolore natus ea libero nulla. Nesciunt tempore rerum alias porro quidem voluptas quis ab saepe non ad. Beatae excepturi molestias temporibus maxime animi perspiciatis atque reprehenderit in ab alias. Repellat eum excepturi officiis eos magni obcaecati deserunt, adipisci est, soluta inventore, aperiam enim similique! Cum quisquam esse ea aperiam quia? Quas facilis pariatur quod, officia et illum ex commodi animi asperiores ipsa eos itaque voluptates placeat fugit quidem officiis impedit quibusdam sed consequatur accusamus recusandae praesentium est. A officia suscipit cumque quidem quibusdam at culpa voluptates molestiae voluptatum hic maxime cum, perspiciatis architecto voluptatem, aspernatur magni, delectus quasi ipsam laboriosam vero repudiandae beatae. Numquam ut architecto, repellendus accusantium corporis, laudantium unde rerum in aliquam, et perferendis aliquid. Illo, expedita corrupti, minima, maiores nulla excepturi laboriosam perspiciatis fuga vitae ipsa quod dolores! Consectetur excepturi sed non ipsa suscipit, perferendis magnam fugit iium similique sint, sit labore autem dolorem. Vel, reprehenderit minus. Minus, ullam cupiditate possimus error optio, neque at expedita dolor sapiente nisi quam quasi ab iste ipsum repudiandae doloribus vero numquam ipsam rerum dicta. Est corrupti nesciunt praesentium, magnam voluptatibus distinctio repellat itaque consequuntur sunt asperiores soluta possimus voluptas molestiae! Pariatur voluptates ex quae ea assumenda neque quas magni aliquam laboriosam ratione.
      </main>
    </div>
  );
}
